In [2]:
import pandas as pd

In [8]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [9]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [10]:
pd.__version__

'2.3.1'

In [12]:
record_count = len(df)

In [13]:
print(record_count)

9704


In [15]:
print(df['fuel_type'].value_counts())

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64


In [20]:
print(df['origin'].value_counts())

origin
Europe    3254
Asia      3247
USA       3203
Name: count, dtype: int64


In [17]:
print(df.isnull().sum())

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64


In [18]:
print(df['fuel_efficiency_mpg'].max())

25.96722204888372


In [19]:
print(df['horsepower'].median())

149.0


In [29]:
asia_cars = df[df['origin'] == 'Asia']

In [30]:
asia_cars.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [33]:
asian_cars_mfe = asia_cars['fuel_efficiency_mpg'].max()
print(asian_cars_mfe)

23.759122836520497


In [37]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

In [35]:
print(hp_med1)

149.0


In [39]:
hp_med2 = df['horsepower'].median()
print(hp_med1)
print(hp_med2)

149.0
149.0


In [40]:
print(df.isnull().sum())

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64


In [43]:
asia_cars_mod = asia_cars[['model_year','vehicle_weight']]
asia_cars_mod

model_year  vehicle_weight
8           2016     2714.219310
12          2010     2783.868974
14          2007     3582.687368
20          2011     2231.808142
21          2016     2659.431451
...          ...             ...
9688        2018     3948.404625
9692        2016     3680.341381
9693        2012     2545.070139
9698        2005     3107.427820
9703        2005     2908.043477

[3247 rows x 2 columns]

In [44]:
first_7_asia_cars_mod = asia_cars_mod.head(7)
first_7_asia_cars_mod

model_year  vehicle_weight
8         2016     2714.219310
12        2010     2783.868974
14        2007     3582.687368
20        2011     2231.808142
21        2016     2659.431451
34        2014     2844.227534
38        2019     3761.994038

In [46]:
X = first_7_asia_cars_mod.to_numpy()
X

array([[2016.        , 2714.21930965],
       [2010.        , 2783.86897424],
       [2007.        , 3582.68736772],
       [2011.        , 2231.8081416 ],
       [2016.        , 2659.43145076],
       [2014.        , 2844.22753389],
       [2019.        , 3761.99403819]])

In [93]:
XTX =  X.T @ X
print("X:\n", X)
print("X.T:\n", X.T)
print("XTX:\n", XTX)

X:
 [[2016.         2714.21930965]
 [2010.         2783.86897424]
 [2007.         3582.68736772]
 [2011.         2231.8081416 ]
 [2016.         2659.43145076]
 [2014.         2844.22753389]
 [2019.         3761.99403819]]
X.T:
 [[2016.         2010.         2007.         2011.         2016.
  2014.         2019.        ]
 [2714.21930965 2783.86897424 3582.68736772 2231.8081416  2659.43145076
  2844.22753389 3761.99403819]]
XTX:
 [[28373339.         41431216.5073268 ]
 [41431216.5073268  62248334.33150762]]


In [52]:
import numpy as np
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [94]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 1.25380877e-06, -8.34509443e-07],
       [-8.34509443e-07,  5.71497081e-07]])

In [56]:
print("XTX:\n", XTX)
print("\nInverse of XTX:\n", XTX_inv)

XTX:
 [[28373339.         41431216.5073268 ]
 [41431216.5073268  62248334.33150762]]

Inverse of XTX:
 [[ 1.25380877e-06 -8.34509443e-07]
 [-8.34509443e-07  5.71497081e-07]]


In [90]:
step = XTX_inv @ X.T 
print(step)


[[ 2.62636846e-04  1.96990690e-04 -4.73392228e-04  6.58944477e-04
   3.08357831e-04  1.51636137e-04 -6.07979633e-04]
 [-1.31202622e-04 -8.63909858e-05  3.72634923e-04 -4.02726650e-04
  -1.62513724e-04 -5.52342829e-05  4.65094049e-04]]


In [91]:
w = step @ y
w

array([0.5049067 , 0.01386421])

In [92]:
total_sum = np.sum(w)
print(total_sum)

0.5187709081074054
